import { format, addDays, startOfDay, setHours, setMinutes } from "date-fns";

interface Session {
  id: string;
  title: string;
  duration: number;
  completed: boolean;
}

interface DayData {
  day: number;
  sessions: Session[];
  isToday?: boolean;
  isCompleted?: boolean;
}

interface CalendarEvent {
  title: string;
  description?: string;
  startDate: Date;
  endDate: Date;
  location?: string;
}

// Generate unique ID for iCal events
function generateUID(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}@focusflow.app`;
}

// Format date for iCal (YYYYMMDDTHHMMSS)
function formatICalDate(date: Date): string {
  return format(date, "yyyyMMdd'T'HHmmss");
}

// Escape special characters in iCal text
function escapeICalText(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/;/g, '\\;')
    .replace(/,/g, '\\,')
    .replace(/\n/g, '\\n');
}

// Create a single iCal event
function createICalEvent(event: CalendarEvent): string {
  const lines = [
    'BEGIN:VEVENT',
    `UID:${generateUID()}`,
    `DTSTAMP:${formatICalDate(new Date())}`,
    `DTSTART:${formatICalDate(event.startDate)}`,
    `DTEND:${formatICalDate(event.endDate)}`,
    `SUMMARY:${escapeICalText(event.title)}`,
  ];

  if (event.description) {
    lines.push(`DESCRIPTION:${escapeICalText(event.description)}`);
  }

  if (event.location) {
    lines.push(`LOCATION:${escapeICalText(event.location)}`);
  }

  lines.push('END:VEVENT');
  return lines.join('\r\n');
}

// Generate iCal content from roadmap data
export function generateICalContent(
  roadmapData: DayData[],
  courseName: string = "Learning Session",
  startDate: Date = new Date(),
  defaultStartHour: number = 9
): string {
  const events: string[] = [];
  
  roadmapData.forEach((day) => {
    const dayDate = addDays(startOfDay(startDate), day.day - 1);
    let currentHour = defaultStartHour;
    let currentMinute = 0;

    day.sessions.forEach((session) => {
      const eventStart = setMinutes(setHours(dayDate, currentHour), currentMinute);
      const eventEnd = new Date(eventStart.getTime() + session.duration * 60 * 1000);

      events.push(createICalEvent({
        title: `📚 ${session.title}`,
        description: `${courseName} - Day ${day.day}\nDuration: ${session.duration} minutes\n\nPowered by FocusFlow`,
        startDate: eventStart,
        endDate: eventEnd,
      }));

      // Add 5 minute break between sessions
      const totalMinutes = currentMinute + session.duration + 5;
      currentHour += Math.floor(totalMinutes / 60);
      currentMinute = totalMinutes % 60;
    });
  });

  const calendar = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//FocusFlow//Learning Schedule//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeICalText(courseName)}`,
    ...events,
    'END:VCALENDAR',
  ].join('\r\n');

  return calendar;
}

// Download iCal file
export function downloadICalFile(content: string, filename: string = "learning-schedule.ics"): void {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Generate Google Calendar URL for a single event
export function generateGoogleCalendarUrl(event: CalendarEvent): string {
  const formatGoogleDate = (date: Date) => format(date, "yyyyMMdd'T'HHmmss");
  
  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: event.title,
    dates: `${formatGoogleDate(event.startDate)}/${formatGoogleDate(event.endDate)}`,
    details: event.description || '',
    location: event.location || '',
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

// Generate Google Calendar URL for adding all events (opens multiple tabs - not ideal)
// For bulk add, .ics import is recommended
export function generateGoogleCalendarImportUrl(): string {
  return 'https://calendar.google.com/calendar/u/0/r/settings/export';
}

// Format schedule summary for sharing
export function generateScheduleSummary(roadmapData: DayData[], courseName: string): string {
  const totalSessions = roadmapData.reduce((sum, d) => sum + d.sessions.length, 0);
  const totalMinutes = roadmapData.reduce(
    (sum, d) => sum + d.sessions.reduce((s, session) => s + session.duration, 0),
    0
  );
  const hours = Math.floor(totalMinutes / 60);
  const minutes = totalMinutes % 60;

  return `📚 ${courseName}\n` +
    `📅 ${roadmapData.length} days\n` +
    `✨ ${totalSessions} sessions\n` +
    `⏱️ ${hours}h ${minutes}m total\n\n` +
    `Generated by FocusFlow`;
}
